version: "3"

services:
  blog:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./blog:/blog
      - ./medium:/medium
      - ./manage.py:/manage.py
    command: >
      sh -c "./manage.py wait_for_db &&
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=blog
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
        - db
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5445:5432"

  hasura:
    image: hasura/graphql-engine:v1.2.0
    # restart: always``
    ports:
      - "8080:8080"
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:supersecretpassword@db:5432/
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    depends_on:
      - db